---
apiVersion: v1
kind: Pod
metadata:
  name: simpleapp
  labels:
    app: simpleapp
spec:
  containers:
    - name: simpleapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        timeoutSeconds: 2
        periodSeconds: 2
