---
apiVersion: v1
kind: Pod
metadata:
  name: SimpleApp
  labels:
    app: SimpleApp
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80x
  livenessProbe:
    httpGet:
      path: /
      port: 80x
    initialDelaySeconds: 1
    periodSeconds: 10
    timeoutSeconds: 1
