---
apiVersion: v1
kind: Pod
metadata:
  name: simpleapp-pod
spec:
  containers:
    - name: simpleapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: SECRET_USERNAME
          value: "insert_secret_username_here"
        - name: SECRET_PASSWORD
          value: "insert_secret_password_here"
