apiVersion: v1
kind: Pod
metadata:
  name: SimpleApp-pod
  labels:
    app: SimpleApp
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    hostPath:
      path: /var/lib/data
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 2