---
apiVersion: v1
kind: Pod
metadata:
  name: SimpleApp-pod
  labels:
    app: SimpleApp
spec:
  containers:
    - name: SimpleApp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 10
        timeoutSeconds: 1
      readinessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 2
