apiVersion: v1
kind: Pod
metadata:
  name: simple-app-pod
  labels:
    app: SimpleApp
    env: prod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80